package com.example.simondice

import android.content.Context
import androidx.compose.runtime.MutableState
import androidx.compose.runtime.mutableStateOf
import androidx.compose.ui.graphics.Color

/**
 * Class that contains the data of the game
 * @property round actual round
 * @property roundState state of the round
 * @property UserSecuence user secuence introduced by the user
 * @property botSecuence bot secuence generated by the bot
 * @property record record of the game
 *
 */
object Data {
    var round = mutableStateOf(0)
    var playStatus = mutableStateOf("Start")
    var UserSecuence = mutableListOf<Int>()
    var botSecuence = mutableListOf<Int>()
    var record = mutableStateOf(0)
    var state = State.START
    var colors = listOf(
        MyColors.BLUE.color,
        MyColors.GREEN.color,
        MyColors.RED.color,
        MyColors.YELLOW.color
    )
    var colorsMyColors = MyColors.values()
    var colorFlag: Color = Color.White

}

/**
 * Enum class that contains the colors of the game
 * @property value value of the color
 */
enum class MyColors(val color: MutableState<Color>){
    // go from 0 to 3
    BLUE(mutableStateOf(Color.Blue)),
    GREEN(mutableStateOf(Color.Green)),
    RED(mutableStateOf(Color.Red)),
    YELLOW(mutableStateOf(Color.Yellow))
}

/**
 * Enum class that contains the states of the game
 */
enum class State {
    START,
    SEQUENCE,
    WAITING,
    INPUT,
    CHECKING,
    FINISH
}